/**
 * Login Page - Generated by Locofy from Figma Design
 * Design: Modern Login with gradient background and card layout
 * 
 * This is a TEST COMPONENT to verify the design integration workflow.
 * When pushed, this should trigger the workflow and attempt to merge
 * this design with the existing LoginPage in Saleslabdev/frontend.
 */

import { Box, Button, TextField, Typography, Card, CardContent, Stack, InputAdornment, IconButton, Divider } from "@mui/material";
import { Visibility, VisibilityOff, Email, Lock, Google, Apple } from "@mui/icons-material";
import { useState } from "react";

const Login = () => {
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleClickShowPassword = () => setShowPassword(!showPassword);

  return (
    <Box
      sx={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        padding: "20px",
      }}
    >
      <Card
        sx={{
          maxWidth: 440,
          width: "100%",
          borderRadius: "24px",
          boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
          overflow: "visible",
        }}
      >
        <CardContent sx={{ padding: "48px 40px" }}>
          {/* Logo Section */}
          <Box sx={{ textAlign: "center", marginBottom: "32px" }}>
            <Box
              sx={{
                width: 64,
                height: 64,
                borderRadius: "16px",
                background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                margin: "0 auto 16px",
              }}
            >
              <Typography sx={{ color: "white", fontSize: 28, fontWeight: 700 }}>V</Typography>
            </Box>
            <Typography
              variant="h4"
              sx={{
                fontWeight: 700,
                color: "#1a1a2e",
                marginBottom: "8px",
              }}
            >
              Welcome Back
            </Typography>
            <Typography
              sx={{
                color: "#666",
                fontSize: "14px",
              }}
            >
              Sign in to continue to your account
            </Typography>
          </Box>

          {/* Form Section */}
          <Stack spacing={3}>
            {/* Email Field */}
            <TextField
              fullWidth
              placeholder="Email Address"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Email sx={{ color: "#999" }} />
                  </InputAdornment>
                ),
              }}
              sx={{
                "& .MuiOutlinedInput-root": {
                  borderRadius: "12px",
                  backgroundColor: "#f8f9fa",
                  "& fieldset": {
                    borderColor: "transparent",
                  },
                  "&:hover fieldset": {
                    borderColor: "#667eea",
                  },
                  "&.Mui-focused fieldset": {
                    borderColor: "#667eea",
                  },
                },
              }}
            />

            {/* Password Field */}
            <TextField
              fullWidth
              type={showPassword ? "text" : "password"}
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Lock sx={{ color: "#999" }} />
                  </InputAdornment>
                ),
                endAdornment: (
                  <InputAdornment position="end">
                    <IconButton onClick={handleClickShowPassword} edge="end">
                      {showPassword ? <VisibilityOff /> : <Visibility />}
                    </IconButton>
                  </InputAdornment>
                ),
              }}
              sx={{
                "& .MuiOutlinedInput-root": {
                  borderRadius: "12px",
                  backgroundColor: "#f8f9fa",
                  "& fieldset": {
                    borderColor: "transparent",
                  },
                  "&:hover fieldset": {
                    borderColor: "#667eea",
                  },
                  "&.Mui-focused fieldset": {
                    borderColor: "#667eea",
                  },
                },
              }}
            />

            {/* Forgot Password Link */}
            <Box sx={{ textAlign: "right" }}>
              <Typography
                component="a"
                href="#"
                sx={{
                  color: "#667eea",
                  fontSize: "14px",
                  textDecoration: "none",
                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                Forgot Password?
              </Typography>
            </Box>

            {/* Sign In Button */}
            <Button
              fullWidth
              variant="contained"
              sx={{
                padding: "14px",
                borderRadius: "12px",
                fontSize: "16px",
                fontWeight: 600,
                textTransform: "none",
                background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                boxShadow: "0 8px 24px rgba(102, 126, 234, 0.4)",
                "&:hover": {
                  background: "linear-gradient(135deg, #5a6fd6 0%, #6a4190 100%)",
                  boxShadow: "0 12px 28px rgba(102, 126, 234, 0.5)",
                },
              }}
            >
              Sign In
            </Button>

            {/* Divider */}
            <Divider sx={{ my: 2 }}>
              <Typography sx={{ color: "#999", fontSize: "12px" }}>OR</Typography>
            </Divider>

            {/* Social Login Buttons */}
            <Stack direction="row" spacing={2}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<Google />}
                sx={{
                  padding: "12px",
                  borderRadius: "12px",
                  borderColor: "#e0e0e0",
                  color: "#333",
                  textTransform: "none",
                  "&:hover": {
                    borderColor: "#667eea",
                    backgroundColor: "rgba(102, 126, 234, 0.04)",
                  },
                }}
              >
                Google
              </Button>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<Apple />}
                sx={{
                  padding: "12px",
                  borderRadius: "12px",
                  borderColor: "#e0e0e0",
                  color: "#333",
                  textTransform: "none",
                  "&:hover": {
                    borderColor: "#667eea",
                    backgroundColor: "rgba(102, 126, 234, 0.04)",
                  },
                }}
              >
                Apple
              </Button>
            </Stack>
          </Stack>

          {/* Footer */}
          <Box sx={{ textAlign: "center", marginTop: "32px" }}>
            <Typography sx={{ color: "#666", fontSize: "14px" }}>
              Need support?{" "}
              <Typography
                component="a"
                href="mailto:support@vitavirtues.com"
                sx={{
                  color: "#667eea",
                  textDecoration: "none",
                  fontWeight: 500,
                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                support@vitavirtues.com
              </Typography>
            </Typography>
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

export default Login;
