/**
 * Login Page Styles - Generated by Locofy
 * These are the extracted style constants from the Figma design
 */

export const loginStyles = {
  // Container
  pageContainer: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "20px",
  },

  // Card
  card: {
    maxWidth: 440,
    width: "100%",
    borderRadius: "24px",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
    overflow: "visible",
  },

  cardContent: {
    padding: "48px 40px",
  },

  // Logo
  logoContainer: {
    textAlign: "center",
    marginBottom: "32px",
  },

  logoBox: {
    width: 64,
    height: 64,
    borderRadius: "16px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 16px",
  },

  logoText: {
    color: "white",
    fontSize: 28,
    fontWeight: 700,
  },

  // Typography
  heading: {
    fontWeight: 700,
    color: "#1a1a2e",
    marginBottom: "8px",
  },

  subheading: {
    color: "#666",
    fontSize: "14px",
  },

  // Input Fields
  textField: {
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
      backgroundColor: "#f8f9fa",
      "& fieldset": {
        borderColor: "transparent",
      },
      "&:hover fieldset": {
        borderColor: "#667eea",
      },
      "&.Mui-focused fieldset": {
        borderColor: "#667eea",
      },
    },
  },

  // Buttons
  primaryButton: {
    padding: "14px",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: 600,
    textTransform: "none",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    boxShadow: "0 8px 24px rgba(102, 126, 234, 0.4)",
    "&:hover": {
      background: "linear-gradient(135deg, #5a6fd6 0%, #6a4190 100%)",
      boxShadow: "0 12px 28px rgba(102, 126, 234, 0.5)",
    },
  },

  socialButton: {
    padding: "12px",
    borderRadius: "12px",
    borderColor: "#e0e0e0",
    color: "#333",
    textTransform: "none",
    "&:hover": {
      borderColor: "#667eea",
      backgroundColor: "rgba(102, 126, 234, 0.04)",
    },
  },

  // Links
  link: {
    color: "#667eea",
    textDecoration: "none",
    "&:hover": {
      textDecoration: "underline",
    },
  },

  // Colors (Design Tokens)
  colors: {
    primary: "#667eea",
    primaryDark: "#5a6fd6",
    secondary: "#764ba2",
    secondaryDark: "#6a4190",
    text: "#1a1a2e",
    textSecondary: "#666",
    textMuted: "#999",
    background: "#f8f9fa",
    border: "#e0e0e0",
  },
};

export default loginStyles;
